definitions:
  big.Int:
    type: object
  model.SignRequest:
    properties:
      csr:
        example: sd
        type: string
      expiration:
        example: 24h
        type: string
      hostnames:
        example:
        - localhost
        items:
          type: string
        type: array
    type: object
  net.IPNet:
    properties:
      ip:
        description: network number
        items:
          type: integer
        type: array
      mask:
        description: network mask
        items:
          type: integer
        type: array
    type: object
  pkix.AttributeTypeAndValue:
    properties:
      type:
        items:
          type: integer
        type: array
      value: {}
    type: object
  pkix.Extension:
    properties:
      critical:
        type: boolean
      id:
        items:
          type: integer
        type: array
      value:
        items:
          type: integer
        type: array
    type: object
  pkix.Name:
    properties:
      commonName:
        type: string
      country:
        items:
          type: string
        type: array
      extraNames:
        description: |-
          ExtraNames contains attributes to be copied, raw, into any marshaled
          distinguished names. Values override any attributes with the same OID.
          The ExtraNames field is not populated when parsing, see Names.
        items:
          $ref: '#/definitions/pkix.AttributeTypeAndValue'
        type: array
      locality:
        items:
          type: string
        type: array
      names:
        description: |-
          Names contains all parsed attributes. When parsing distinguished names,
          this can be used to extract non-standard attributes that are not parsed
          by this package. When marshaling to RDNSequences, the Names field is
          ignored, see ExtraNames.
        items:
          $ref: '#/definitions/pkix.AttributeTypeAndValue'
        type: array
      organization:
        items:
          type: string
        type: array
      organizationalUnit:
        items:
          type: string
        type: array
      postalCode:
        items:
          type: string
        type: array
      province:
        items:
          type: string
        type: array
      serialNumber:
        type: string
      streetAddress:
        items:
          type: string
        type: array
    type: object
  revoke.JsonRevokeRequest:
    properties:
      authority_key_id:
        type: string
      reason:
        description: See https://www.rfc-editor.org/rfc/rfc5280#section-5.3.1 Use
          written out code, e.g. "superseded".
        type: string
      serial:
        type: string
    type: object
  url.URL:
    properties:
      forceQuery:
        description: append a query ('?') even if RawQuery is empty
        type: boolean
      fragment:
        description: fragment for references, without '#'
        type: string
      host:
        description: host or host:port (see Hostname and Port methods)
        type: string
      omitHost:
        description: do not emit empty host (authority)
        type: boolean
      opaque:
        description: encoded opaque data
        type: string
      path:
        description: path (relative paths may omit leading slash)
        type: string
      rawFragment:
        description: encoded fragment hint (see EscapedFragment method)
        type: string
      rawPath:
        description: encoded path hint (see EscapedPath method)
        type: string
      rawQuery:
        description: encoded query values, without '?'
        type: string
      scheme:
        type: string
      user:
        allOf:
        - $ref: '#/definitions/url.Userinfo'
        description: username and password information
    type: object
  url.Userinfo:
    type: object
  x509.Certificate:
    properties:
      authorityKeyId:
        items:
          type: integer
        type: array
      basicConstraintsValid:
        description: |-
          BasicConstraintsValid indicates whether IsCA, MaxPathLen,
          and MaxPathLenZero are valid.
        type: boolean
      crldistributionPoints:
        description: CRL Distribution Points
        items:
          type: string
        type: array
      dnsnames:
        description: |-
          Subject Alternate Name values. (Note that these values may not be valid
          if invalid values were contained within a parsed certificate. For
          example, an element of DNSNames may not be a valid DNS domain name.)
        items:
          type: string
        type: array
      emailAddresses:
        items:
          type: string
        type: array
      excludedDNSDomains:
        items:
          type: string
        type: array
      excludedEmailAddresses:
        items:
          type: string
        type: array
      excludedIPRanges:
        items:
          $ref: '#/definitions/net.IPNet'
        type: array
      excludedURIDomains:
        items:
          type: string
        type: array
      extKeyUsage:
        description: Sequence of extended key usages.
        items:
          type: integer
        type: array
      extensions:
        description: |-
          Extensions contains raw X.509 extensions. When parsing certificates,
          this can be used to extract non-critical extensions that are not
          parsed by this package. When marshaling certificates, the Extensions
          field is ignored, see ExtraExtensions.
        items:
          $ref: '#/definitions/pkix.Extension'
        type: array
      extraExtensions:
        description: |-
          ExtraExtensions contains extensions to be copied, raw, into any
          marshaled certificates. Values override any extensions that would
          otherwise be produced based on the other fields. The ExtraExtensions
          field is not populated when parsing certificates, see Extensions.
        items:
          $ref: '#/definitions/pkix.Extension'
        type: array
      inhibitAnyPolicy:
        description: |-
          InhibitAnyPolicy and InhibitAnyPolicyZero indicate the presence and value
          of the inhibitAnyPolicy extension.

          The value of InhibitAnyPolicy indicates the number of additional
          certificates in the path after this certificate that may use the
          anyPolicy policy OID to indicate a match with any other policy.

          When parsing a certificate, a positive non-zero InhibitAnyPolicy means
          that the field was specified, -1 means it was unset, and
          InhibitAnyPolicyZero being true mean that the field was explicitly set to
          zero. The case of InhibitAnyPolicy==0 with InhibitAnyPolicyZero==false
          should be treated equivalent to -1 (unset).
        type: integer
      inhibitAnyPolicyZero:
        description: |-
          InhibitAnyPolicyZero indicates that InhibitAnyPolicy==0 should be
          interpreted as an actual maximum path length of zero. Otherwise, that
          combination is interpreted as InhibitAnyPolicy not being set.
        type: boolean
      inhibitPolicyMapping:
        description: |-
          InhibitPolicyMapping and InhibitPolicyMappingZero indicate the presence
          and value of the inhibitPolicyMapping field of the policyConstraints
          extension.

          The value of InhibitPolicyMapping indicates the number of additional
          certificates in the path after this certificate that may use policy
          mapping.

          When parsing a certificate, a positive non-zero InhibitPolicyMapping
          means that the field was specified, -1 means it was unset, and
          InhibitPolicyMappingZero being true mean that the field was explicitly
          set to zero. The case of InhibitPolicyMapping==0 with
          InhibitPolicyMappingZero==false should be treated equivalent to -1
          (unset).
        type: integer
      inhibitPolicyMappingZero:
        description: |-
          InhibitPolicyMappingZero indicates that InhibitPolicyMapping==0 should be
          interpreted as an actual maximum path length of zero. Otherwise, that
          combination is interpreted as InhibitAnyPolicy not being set.
        type: boolean
      ipaddresses:
        items:
          items:
            type: integer
          type: array
        type: array
      isCA:
        type: boolean
      issuer:
        $ref: '#/definitions/pkix.Name'
      issuingCertificateURL:
        items:
          type: string
        type: array
      keyUsage:
        type: integer
      maxPathLen:
        description: |-
          MaxPathLen and MaxPathLenZero indicate the presence and
          value of the BasicConstraints' "pathLenConstraint".

          When parsing a certificate, a positive non-zero MaxPathLen
          means that the field was specified, -1 means it was unset,
          and MaxPathLenZero being true mean that the field was
          explicitly set to zero. The case of MaxPathLen==0 with MaxPathLenZero==false
          should be treated equivalent to -1 (unset).

          When generating a certificate, an unset pathLenConstraint
          can be requested with either MaxPathLen == -1 or using the
          zero value for both MaxPathLen and MaxPathLenZero.
        type: integer
      maxPathLenZero:
        description: |-
          MaxPathLenZero indicates that BasicConstraintsValid==true
          and MaxPathLen==0 should be interpreted as an actual
          maximum path length of zero. Otherwise, that combination is
          interpreted as MaxPathLen not being set.
        type: boolean
      notAfter:
        description: Validity bounds.
        type: string
      notBefore:
        description: Validity bounds.
        type: string
      ocspserver:
        description: RFC 5280, 4.2.2.1 (Authority Information Access)
        items:
          type: string
        type: array
      permittedDNSDomains:
        items:
          type: string
        type: array
      permittedDNSDomainsCritical:
        description: Name constraints
        type: boolean
      permittedEmailAddresses:
        items:
          type: string
        type: array
      permittedIPRanges:
        items:
          $ref: '#/definitions/net.IPNet'
        type: array
      permittedURIDomains:
        items:
          type: string
        type: array
      policies:
        description: |-
          Policies contains all policy identifiers included in the certificate.
          See CreateCertificate for context about how this field and the PolicyIdentifiers field
          interact.
          In Go 1.22, encoding/gob cannot handle and ignores this field.
        items:
          $ref: '#/definitions/x509.OID'
        type: array
      policyIdentifiers:
        description: |-
          PolicyIdentifiers contains asn1.ObjectIdentifiers, the components
          of which are limited to int32. If a certificate contains a policy which
          cannot be represented by asn1.ObjectIdentifier, it will not be included in
          PolicyIdentifiers, but will be present in Policies, which contains all parsed
          policy OIDs.
          See CreateCertificate for context about how this field and the Policies field
          interact.
        items:
          items:
            type: integer
          type: array
        type: array
      policyMappings:
        description: PolicyMappings contains a list of policy mappings included in
          the certificate.
        items:
          $ref: '#/definitions/x509.PolicyMapping'
        type: array
      publicKey: {}
      publicKeyAlgorithm:
        type: integer
      raw:
        description: Complete ASN.1 DER content (certificate, signature algorithm
          and signature).
        items:
          type: integer
        type: array
      rawIssuer:
        description: DER encoded Issuer
        items:
          type: integer
        type: array
      rawSubject:
        description: DER encoded Subject
        items:
          type: integer
        type: array
      rawSubjectPublicKeyInfo:
        description: DER encoded SubjectPublicKeyInfo.
        items:
          type: integer
        type: array
      rawTBSCertificate:
        description: Certificate part of raw ASN.1 DER content.
        items:
          type: integer
        type: array
      requireExplicitPolicy:
        description: |-
          RequireExplicitPolicy and RequireExplicitPolicyZero indicate the presence
          and value of the requireExplicitPolicy field of the policyConstraints
          extension.

          The value of RequireExplicitPolicy indicates the number of additional
          certificates in the path after this certificate before an explicit policy
          is required for the rest of the path. When an explicit policy is required,
          each subsequent certificate in the path must contain a required policy OID,
          or a policy OID which has been declared as equivalent through the policy
          mapping extension.

          When parsing a certificate, a positive non-zero RequireExplicitPolicy
          means that the field was specified, -1 means it was unset, and
          RequireExplicitPolicyZero being true mean that the field was explicitly
          set to zero. The case of RequireExplicitPolicy==0 with
          RequireExplicitPolicyZero==false should be treated equivalent to -1
          (unset).
        type: integer
      requireExplicitPolicyZero:
        description: |-
          RequireExplicitPolicyZero indicates that RequireExplicitPolicy==0 should be
          interpreted as an actual maximum path length of zero. Otherwise, that
          combination is interpreted as InhibitAnyPolicy not being set.
        type: boolean
      serialNumber:
        $ref: '#/definitions/big.Int'
      signature:
        items:
          type: integer
        type: array
      signatureAlgorithm:
        type: integer
      subject:
        $ref: '#/definitions/pkix.Name'
      subjectKeyId:
        items:
          type: integer
        type: array
      unhandledCriticalExtensions:
        description: |-
          UnhandledCriticalExtensions contains a list of extension IDs that
          were not (fully) processed when parsing. Verify will fail if this
          slice is non-empty, unless verification is delegated to an OS
          library which understands all the critical extensions.

          Users can access these extensions using Extensions and can remove
          elements from this slice if they believe that they have been
          handled.
        items:
          items:
            type: integer
          type: array
        type: array
      unknownExtKeyUsage:
        description: Encountered extended key usages unknown to this package.
        items:
          items:
            type: integer
          type: array
        type: array
      uris:
        items:
          $ref: '#/definitions/url.URL'
        type: array
      version:
        type: integer
    type: object
  x509.OID:
    type: object
  x509.PolicyMapping:
    properties:
      issuerDomainPolicy:
        allOf:
        - $ref: '#/definitions/x509.OID'
        description: |-
          IssuerDomainPolicy contains a policy OID the issuing certificate considers
          equivalent to SubjectDomainPolicy in the subject certificate.
      subjectDomainPolicy:
        allOf:
        - $ref: '#/definitions/x509.OID'
        description: |-
          SubjectDomainPolicy contains a OID the issuing certificate considers
          equivalent to IssuerDomainPolicy in the subject certificate.
    type: object
info:
  contact: {}
  description: This is a private certificate authority that builds on top of CFSSL
  title: Certificate Authority
  version: "1.0"
paths:
  /ca:
    post:
      description: Gets the CA public certificate
      produces:
      - text/plain
      responses:
        "200":
          description: OK
      summary: Gets the CA public certificate
  /revoke:
    post:
      consumes:
      - application/json
      description: Revokes a certificate
      parameters:
      - description: Request payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/revoke.JsonRevokeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Revokes a certificate
  /sign:
    post:
      consumes:
      - application/json
      description: The provided certificate will be signed with the root CA certificate.
        The expiration time in hours will be used for the certificate expiration.
        The hostnames will be used for the subject alternative name field. The User
        ID will be used in the common name field.
      parameters:
      - description: Request payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/model.SignRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/x509.Certificate'
      summary: Sign a Certificate Signing Request
swagger: "2.0"
