name: Tests
on:
  push:
    branches:
      - master
      - dev
    pull_request:
      branches:
      - master
      - dev
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker compose -f deployment/test/docker-compose.yml build
      - name: Start the stack
        run: docker compose -f deployment/test/docker-compose.yml up -d db_test
      - name: Run test container
        run: docker compose -f deployment/test/docker-compose.yml run cfssl_test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: /tmp/coverage.out
